- env/Chart.yaml
- env/requirements.yaml
Promote node-demo01 to version 0.0.1
> node-demo01 to 0.0.1

- env/requirements.yaml
Promote simondemo01 to version 0.0.1
> simondemo01 to 0.0.1

- env/requirements.yaml
Promote simondemo01 to version 0.0.2
> simondemo01 to 0.0.2

- env/requirements.yaml
Promote node-demo02 to version 0.0.1
> node-demo02 to 0.0.1

- env/requirements.yaml
Promote node-demo02 to version 0.0.2
> node-demo02 to 0.0.2

- env/requirements.yaml
Promote node-demo02 to version 0.0.3
> node-demo02 to 0.0.3

- env/requirements.yaml
Promote buddhademo-1 to version 0.0.1
> buddhademo-1 to 0.0.1

- env/requirements.yaml
Promote buddhademo-1 to version 0.0.2
> buddhademo-1 to 0.0.2

- env/requirements.yaml
> Delete application buddhademo-1 from this environment

- env/requirements.yaml
> Delete application node-demo01 from this environment

- env/requirements.yaml
> Delete application node-demo02 from this environment

- env/requirements.yaml
> Delete application simondemo01 from this environment

- env/requirements.yaml
Promote easter-demo01 to version 0.0.1
> easter-demo01 to 0.0.1

- env/requirements.yaml
Promote easter-demo01 to version 0.0.2
> easter-demo01 to 0.0.2

- env/requirements.yaml
Promote easter-demo02 to version 0.0.1
> easter-demo02 to 0.0.1

- env/requirements.yaml
Promote easter-demo02 to version 0.0.2
> easter-demo02 to 0.0.2

- env/requirements.yaml
Promote easter-demo03 to version 0.0.1
> easter-demo03 to 0.0.1

- env/requirements.yaml
Promote easter-demo03 to version 0.0.2
> easter-demo03 to 0.0.2

- env/requirements.yaml
Promote croc-hunter-jenkinsx to version 0.0.44
> croc-hunter-jenkinsx to 0.0.44

- env/requirements.yaml
> Delete application croc-hunter-jenkinsx from this environment
